add get trade logs v1
KyberNetwork/reserve-stats pull request #545
Opened 2021-03-16 11:05 UTC by onlylove97

2021-03-16 12:34 UTC, secmask commented
@onlylove97 CI failed, fix it please.

2021-03-17 04:14 UTC, halink0803 requested changes
Now we usdt as main quote, so, please remove all the part related to the ETH (as quote) and ETHUSDT price as well.

2021-03-17 07:08 UTC, halink0803 requested changes
Please check again.

2021-03-17 07:08 UTC, halink0803 commented on tradelogs/storage/postgres/postgres.go
> +		USDTAmount:         ethAmountInWei,
why don't you change this "ethAmountInWei" name?

2021-03-17 10:23 UTC, halink0803 approved these changes

2021-03-17 10:24 UTC, merged